# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykafka < Formula
  desc "Relaxed Kafka TUI for browsing and managing clusters."
  homepage "https://github.com/dubel/lazykafka-dist"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dubel/lazykafka-dist/releases/download/v0.0.1/lazykafka_0.0.1_darwin_amd64.tar.gz"
      sha256 "644a0d1a9dfb55ee1f303f8675086be0994e19b888b35f0167efeeed35c0c768"

      def install
        bin.install "lazykafka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dubel/lazykafka-dist/releases/download/v0.0.1/lazykafka_0.0.1_darwin_arm64.tar.gz"
      sha256 "5c33e0458e6cbe44bf98a5f27657c3bcf529bf9822cde2b77a56dbd49b00511c"

      def install
        bin.install "lazykafka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dubel/lazykafka-dist/releases/download/v0.0.1/lazykafka_0.0.1_linux_amd64.tar.gz"
      sha256 "d4de45bb62b57222d368714266db0ec60cf4af40ebfbdf298c851fae97c32e93"
      def install
        bin.install "lazykafka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dubel/lazykafka-dist/releases/download/v0.0.1/lazykafka_0.0.1_linux_arm64.tar.gz"
      sha256 "ba83a2ffe8a8b905d2753a8bd2f86621d914e24e097d863a8f6bc3cdfec5a271"
      def install
        bin.install "lazykafka"
      end
    end
  end

  test do
    system "#{bin}/lazykafka", "--version"
  end
end
